DROP TABLE IF EXISTS users, tweets;

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  profile_photo TEXT NOT NULL,
  password_hash TEXT NOT NULL
);

CREATE TABLE tweets (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  text VARCHAR(255) NOT NULL
);
