DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tweets CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  profile_photo TEXT NOT NULL,
  password_hash TEXT NOT NULL
);
CREATE TABLE tweets (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  photo_url TEXT NOT NULL,
  caption TEXT NOT NULL,
  tags TEXT []
);
CREATE TABLE comments (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  comment_by BIGINT REFERENCES users(id),
  tweet BIGINT REFERENCES tweets(id),
  comment TEXT NOT NULL
);
